# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bab7b0bdbc820490ae1b7ca9e0fc0ff93608351625eab13611781014b95da980b3369944412415dc33210f9c461ceaa2df8d154c783c694d3ec7f2cf92376e89

test:
  secret_key_base: 353e06a7006aa3c140862c079386b8442041b27fdf5c0f726f9b582fab9655511a926a863dff0933e997f5c2105f859a4e3c317796020fd1ef63b3956f1ce308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
